name: flutter_test_weather
description: A Weather Project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
  image_picker: ^0.8.4+2
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_slidable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile_pic.png
    - assets/images/weatherbgimage.jpg
    - assets/images/weatherlogo.jpg
    - assets/images/wea.png
  